version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/work
    steps:
      - checkout
      - run: echo "Hello, World"
      - run: ls
      - add_ssh_keys:
            fingerprints:
              - "e6:ee:cb:c9:c4:05:21:7a:20:4b:09:0b:01:0d:a5:15"
      - run: sh ./deploy/deploy.sh