version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/work
    steps:
      - checkout
      - run: echo "Hello, World"
      - run: ls
      - add_ssh_keys:
            fingerprints:
              - "90:67:ca:07:40:52:ed:e8:70:57:b0:20:74:be:6e:76"
      - run: sh ./deploy/deploy.sh