version: 2
jobs:
  build:
    docker:
      - image: clang:latest
    steps:
      - checkout
      - run:
          name: practice
          command: |
            echo "hello, world"
            ls -al
